version: '3'
services:

  php:
    build:
      context: ./docker/php
    volumes:
      - ./backend:/var/www/html

  web:
    build:
      context: ./docker/nginx
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"


  db:
    build:
      context: ./docker/mysql
    environment:
      - MYSQL_DATABASE=alx
      - MYSQL_USER=alxuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    ports:
      - "3306:3306"